### ISSUE TITLE
How can I Test source code  without installed plugin in Bim server ?

### ISSUE THREAD

**Issue by raviarsuda05** [opensourceBIM/GltfSerializers#14]
I am trying to do some modifying in plugin as per my requirement but it's hard to debug because I have to always install a plugin in the bim server for see console log.

**Comment by hlg** [comment]
You can write tests, automate the plugin installation or use the LocalDevBimServerStarterJar where you don't have to explicitely build and deploy the plugin, just restart the server and it will load from the target directory in your plugin folder, where your compiler potentially drops incremental builds automatically.
