### ISSUE TITLE
Bim Server 1.5.147 gets stuck while I am using "Binary glTF Serializer 2" for downloading model

### ISSUE THREAD

**Issue by raviarsuda05** [opensourceBIM/GltfSerializers#8]
I upload model with using  "Ifc2x3tc1 (Streaming)" schema. But Problem is  that while I am trying to fetch model from cache with use of Binary "glTF Serializer 2 Searializer" at run time, Bim server gets stuck

**Comment by rubendel** [comment]
That is a pretty useless description. What is in the server log? Is CPU usage high? How much memory is in use by BIMserver? Which Java version? Does the model show in BIMvie.ws?

**Comment by raviarsuda05** [comment]
1)I am not getting server log because of bim server stuck
2) CPU uses 100% 
3) Total Ram is 16 GB while fetch model memory uses will 5 to 6 GB
4) Java version 1.8.0
5) i can see model in BIMie.ws
6) i am getting this issue when i using "ServiceInterface.getDownloadData" api

**Comment by rubendel** [comment]
Does it use 100% of all cores? The bimserver log should be readable even when all cores are busy, assuming you are on a mainstream OS. What limit is set on the JVM heap for BIMserver?

**Comment by raviarsuda05** [comment]
I allocated 8350mb

**Comment by raviarsuda05** [comment]
I got solution. If I set up war file for bim server then caching process fast then jar execution
